# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Demo
  #   url: '#about'
  #   weight: 10
  # - name: Talks
  #   url: '#talks'
  #   weight: 34
  # - name: Presentations
  #   url: '#presentations'
  #   weight: 80
  # - name: Courses
  #   url: courses/
  #   weight: 60
  # - name: Erfahrung
  #   url: '#experience'
  #   weight: 50
  # - name: Publications
  #   url: '#publications'
  #   weight: 22
  - name: Home
    url: '#about'
    weight: 5
  - name: Leistungen
    url: '#skills'
    weight: 10
  - name: Ordination
    url: '#workshops'
    weight: 20
  - name: Kontakt
    url: '#contact'
    weight: 25
  - name: Blog
    url: '#posts'
    weight: 26
  - name: Medizin
    identifier: medizin
    weight: 61
  - name: Science Breakfast
    parent: medizin
    url: '#sciencebreakfasts'
    weight: 10 
  - name: Projekte
    parent: medizin
    url: '#projects'
    weight: 20
  - name: Poster
    parent: medizin
    url: '#posters'
    weight: 30
  - name: Galerie
    url: '#gallery'
    weight: 55
  - name: Auszeichnungen
    url: '#accomplishments'
    weight: 60
