# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Demo
  #   url: '#about'
  #   weight: 10
  # - name: Talks
  #   url: '#talks'
  #   weight: 34
  # - name: Presentations
  #   url: '#presentations'
  #   weight: 80
  # - name: Courses
  #   url: courses/
  #   weight: 60
  # - name: Erfahrung
  #   url: '#experience'
  #   weight: 50
  # - name: Publications
  #   url: '#publications'
  #   weight: 22
  
  #1
  - name: Home
    url: '#about'
    weight: 10
  
  #2
  - name: Ordination
    identifier: ordination
    weight: 20
  - name: Leistungen
    url: '#skills'
    parent: ordination
    weight: 21
  - name: Privatordination
    url: '#workshops'
    parent: ordination
    weight: 22
  - name: Kontakt Ordination
    url: '#contact'
    parent: ordination
    weight: 23
    
  #3
  - name: Blog
    url: '#posts'
    weight: 30
    
  #4
  - name: Info
    identifier: info
    weight: 40
  - name: Galerie
    url: '#gallery'
    parent: info
    weight: 41
  - name: Auszeichnung Zertifikat
    url: '#accomplishments'
    parent: info
    weight: 42
  
  #5
  - name: Projekte
    identifier: projekte
    weight: 50
  - name: Science Breakfast
    parent: projekte
    url: '#sciencebreakfasts'
    weight: 10 
  - name: Medizin Apps
    parent: projekte
    url: '#projects'
    weight: 20
  - name: Poster
    parent: projekte
    url: '#posters'
    weight: 30
    
  #6
  - name: Kontakt
    url: '#contact'
    weight: 60

